### ISSUE TITLE
这个怎么用在arm的机器上，换内核后开不了机。

### ISSUE THREAD

**Issue by cchenziqiang** [UJX6N/bbrplus-4.19#2]

**Comment by cchenziqiang** [comment]
How can this be used on the ARM machine? After changing the kernel, the machine cannot be started.

**Comment by UJX6N** [comment]
4.19没有编译ARM架构的内核。5.10或以上有。

**Comment by cchenziqiang** [comment]
> 4.19没有编译ARM架构的内核。5.10或以上有。

### 可以帮忙看看能不能提供一个arm的吗，有偿

**Comment by UJX6N** [comment]
你在什么环境使用呢？

如果是云上的虚机，比方AWS、华为云、Oracle上的ARM架构虚机，编译出来应该是可以用的。

如果是物理机器，比方ARM架构的路由器、开发板，那就完全无法保证了，驱动大概率不适配。

**Comment by cchenziqiang** [comment]
银河麒麟的桌面系统，4.19.90 aarch64

**Comment by UJX6N** [comment]
那直接编译应该不能用。如果有它内核的源码包，则可以试试。因为特定系统的内核都包含很多它们自己的补丁，特别是驱动。它的包格式是什么的？rpm？那看下能不能找到它的内核源码包。

形如：kernel-什么什么.src.rpm

内核的一般kernel开头的名字，扩展名src.rpm是源码包

**Comment by cchenziqiang** [comment]
我之前试了您提供的4.19的补丁，在4.19的x86的麒麟上是可以用的。

**Comment by UJX6N** [comment]
你用的是ARM版银河麒麟是......飞腾版、海思麒麟版，还是鲲鹏版？或者别的？

**Comment by cchenziqiang** [comment]
银河麒麟，这个是他的镜像链接：

**Comment by UJX6N** [comment]
好的，我研究下

**Comment by cchenziqiang** [comment]
好的，感谢，我的微信是

**Comment by UJX6N** [comment]
编译了一个，可以试下

https://github.com/UJX6N/bbrplus-4.19/releases/tag/4.19.246-bbrplus_aarch64-rpms

**Comment by cchenziqiang** [comment]
好的，非常感谢！我试试看

**Comment by cchenziqiang** [comment]
可以加一下wx  后续可以联系下您  17751788586

**Comment by cchenziqiang** [comment]
您好，我可以通过下载4.19.246内核源码，然后打补丁吗

**Comment by cchenziqiang** [comment]
可以教我一下，您用的什么内核源码吗，我这边安装了开不了机

**Comment by UJX6N** [comment]
就是kernel官网的源码
https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.246.tar.xz

如果是arm64架构物理机，用官方内核很可能开不了机，因为可能没有物理机对应的特定驱动、或需要带签名内核才能开机（具体看下开机的console提示或dmesg回看）。

官网内核比较适合于arm64虚拟机，如果是物理机的话，x86-64一般没问题，arm64物理机很可能不行。

我看下能不能用你系统里的内核的源码，你试下在系统里用
sudo yumdownloader --source kernel

把你现在用的内核的源码拉下来，是一个.src.rpm文件。如果可以拉下来，共享给我看看。

**Comment by UJX6N** [comment]
我找了台虚机装一下你共享的镜像，再研究下

![图片](https://user-images.githubusercontent.com/57297120/174103552-a5c87dac-b284-4d6b-9a0b-4c9e50a1a144.png)

**Comment by cchenziqiang** [comment]
嗯呐 麻烦您了 我明后天看下能不能拉您说的那个src.rpm文件。还有个问题想请教下，您是用的什么虚拟机工具安装镜像的，我也想试试

**Comment by UJX6N** [comment]
> 

我是阿里云上的虚机

**Comment by cchenziqiang** [comment]
嗯嗯好嘞，那麻烦您帮我看一下了

**Comment by cchenziqiang** [comment]
这个是安装您之前提供aarch64的补丁，makeinstallmodule的报错，链接：https://pan.baidu.com/s/18Pwm-RaadNK4V45oWAPeyA 
提取码：pl84

**Comment by cchenziqiang** [comment]
您好，我运行了上次您说的抓取内核源码，源可能有问题，报错是：
Kylin Linux Advanced Server 10 - cdrom                                                                                                                        693  B/s | 3.7 kB     00:05    
没有可用的软件包 kernel-4.19.90-24.4.v2101.ky10.src。
退出由于严格设置。
Error: 没有可用的软件包 kernel-4.19.90-24.4.v2101.ky10.src。

然后我找到了这个源： https://update.cs2c.com.cn/NS/V10/V10SP1/os/adv/lic/base/aarch64/Packages/

![image](https://user-images.githubusercontent.com/45416504/174423810-2e8aeb8e-fe99-431d-b9e9-f9f1b72f18ba.png)
sh上面有这个内核 可以供参考使用吗

**Comment by UJX6N** [comment]
搞定了，请下载这个版本：

https://github.com/UJX6N/bbrplus-4.19/releases/tag/4.19.248-bbrplus_aarch64-rpm

kernel-4.19.118-bbrplus.ky10   ——这版本用麒麟编译，带[cjktty](https://github.com/zhmars/cjktty-patches)补丁（原麒麟内核也有，可在控制台显示中日韩字符，未验证）
kernel-4.19.248-bbrplus  ——常规的版本，麒麟可用，但不带cjktty补丁，因为补丁支持不了高版本4.19

注意！需要先禁用SELINUX
------------------------------
vim /etc/selinux/config
改
`SELINUX=enforcing`
为
`SELINUX=disabled`

<BR>

另外你发给我的ISO应该是测试版，所以EFI固件位置有些奇怪（在/boot/efi/EFI/test2/），不过没关系可以用，但最好根据这个情况，执行以下命令更新grub配置文件的软链：
```
unlink /etc/grub2-efi.cfg
unlink /boot/grub2/grubenv
ln -s /boot/efi/EFI/test2/grub.cfg /etc/grub2-efi.cfg
ln -s /boot/efi/EFI/test2/grubenv /boot/grub2/grubenv
grub2-mkconfig -o /etc/grub2-efi.cfg
```
然后再安装内核。

总结来说，就是：**1）先禁用SELINUX；2）再更新grub配置文件软链；3）最后安装内核rpm**

<BR>

你这个新找到的更新源不错，我已经改成这个在线源了，可以更新到V10 SP2。

改源
-----------------------------
vim /etc/yum.repos.d/kylin_aarch64.repo

内容改为
```
[ks10-adv-base]
name=Kylin Linux Advanced Server 10 - Base
baseurl=http://update.cs2c.com.cn/NS/V10/V10SP2/os/adv/lic/base/aarch64/
gpgcheck=0
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-kylin-release

[ks10-adv-updates]
name=Kylin Linux Advanced Server 10 - Updates
baseurl=http://update.cs2c.com.cn/NS/V10/V10SP2/os/adv/lic/updates/aarch64/
gpgcheck=0
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-kylin-release
```

**Comment by cchenziqiang** [comment]
真的非常感谢您，我这边安装上了，可以留个联系方式啥的吗，这个是学校老师的任务，等老师的物理机安装成功后，给您酬劳

**Comment by UJX6N** [comment]
> 真的非常感谢您，我这边安装上了，可以留个联系方式啥的吗，这个是学校老师的任务，等老师的物理机安装成功后，给您酬劳

不用了，我也顺便研究下。我从来不在arm64上用CentOS类的系统，都是Debian或Ubuntu，所以开始弄的时候比较够呛。另外吐槽下麒麟没有给普通用户开放源码，估计正式商用客户才能拿到。

**Comment by cchenziqiang** [comment]
我们安装在虚拟机上可以，安装到对应镜像的物理机就一直重启，您有相关经历知道为什么吗

**Comment by cchenziqiang** [comment]
没有报错就是一直重启

**Comment by UJX6N** [comment]
> 没有报错就是一直重启

248和118的内核都重启吗？

关闭了SELINUX没有？确定 /etc/selinux/config 里是
`SELINUX=disabled`

另外console屏幕上有什么显示？看不到的话，可以dmesg回看下

**Comment by UJX6N** [comment]
另外物理机的话，要看下主板BIOS设置里的

**secure boot**

是否启用了，需要disable

**Comment by cchenziqiang** [comment]
他这个主板。。直接没有secure boot。。疑惑了
![83b92c99538189c2f60ce54d2043c7c](https://user-images.githubusercontent.com/45416504/175893986-bff5088f-8b5b-417d-bdbe-5535df7a3d64.jpg)
![040e7434f6d3599b6b9dacf7a583559](https://user-images.githubusercontent.com/45416504/175894008-b7f6ce66-d24e-4dc0-8592-da39096d1046.jpg)
![4ebabbfcf2249412ac538fffdce5a0b](https://user-images.githubusercontent.com/45416504/175894031-718874a4-2e88-461e-8dba-a7d2b1bece43.jpg)
![5d0663c3bc2439bde40660522f3a9c6](https://user-images.githubusercontent.com/45416504/175894038-455d3804-e27f-4c85-9ba8-d255049699e7.jpg)
![e0b82e92d0d673a69a7ae05372a4cd0](https://user-images.githubusercontent.com/45416504/175894045-710e3fdd-e777-4583-ae94-5c61857c2fe0.jpg)

**Comment by cchenziqiang** [comment]
换内核后，到这个界面就启动不了，自动重启了
![ec7d56ada7eb5a5b27cadfe3e2f65c6](https://user-images.githubusercontent.com/45416504/175895138-d82d10ff-454c-4983-9d10-b12e47c8a586.jpg)

**Comment by UJX6N** [comment]
只能我再研究一下了，看能不能搞到飞腾版的银河麒麟的内核源码😧😥

**Comment by cchenziqiang** [comment]
嗯嗯，真的是太谢谢您了

**Comment by UJX6N** [comment]
> 嗯嗯，真的是太谢谢您了

主板“启动”页签里的“兼容模式”......如果设为“打开”看有没有帮助（我也不知道兼容模式是啥😅）

**Comment by cchenziqiang** [comment]
试了下，没有效果。。

**Comment by UJX6N** [comment]
> 试了下，没有效果。。

😅😅

**Comment by cchenziqiang** [comment]
老哥，可以给个邮箱吗，我找麒麟要来了源码，可以发给您帮我看一下吗

**Comment by UJX6N** [comment]
> 老哥，可以给个邮箱吗，我找麒麟要来了源码，可以发给您帮我看一下吗

ujx6n@yahoo.com

**Comment by Alvin1986** [comment]
大佬，aarch64的设备 装centos系统 很多服务无法启动 这是缺少什么补丁?![-eb83950253b8a62.png](https://github.com/UJX6N/bbrplus-4.19/assets/125835237/f9afbf87-8917-42f9-ae3a-b07c55595fc9)

**Comment by vmos0** [comment]
UJX6N大佬是否有考虑BBR2和BBR3补丁？

**Comment by UJX6N** [comment]
> UJX6N大佬是否有考虑BBR2和BBR3补丁？

暂时没有考虑
